name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONFIGURE_PRESET: "linux-default-release"
  BUILD_PRESET: "linux-ci"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake --preset ${{env.CONFIGURE_PRESET}} 

    - name: Build
      run: cmake --build --preset ${{env.BUILD_PRESET}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --preset ${{env.BUILD_PRESET}}
      
