name: CMake

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CONFIGURE_PRESET: "linux-default-release"
  BUILD_PRESET: "linux-ci"
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: lukka/get-cmake@latest

      - uses: actions/cache@v2
        id: cache
        with:
          path: ./vcpkg
          key: ${{ runner.os }}-${{ hashFiles('vcpkg/**') }}

      - name: bootstrap vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        shell: "bash"
        run: ./vcpkg/bootstrap-vcpkg.sh

      - name: "Setup NuGet Credentials"
        shell: "bash"
        # Replace <OWNER> with your organization name
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/mathisloge/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "mathisloge"
          -password "${{ secrets.GITHUB_TOKEN }}"

      - name: Configure CMake
        run: cmake --preset ${{env.CONFIGURE_PRESET}}

      - name: Build
        run: cmake --build --preset ${{env.BUILD_PRESET}}

      - name: Test
        run: ctest --preset ${{env.BUILD_PRESET}}
